name: Publish to GitHub Packages and Create Release

on:
  push:
    branches:
      - main  # Only trigger on commits pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        registry-url: 'https://npm.pkg.github.com'

    - name: Install dependencies with Yarn
      run: yarn install

    - name: Set package version
      run: |
        echo "Updating version to 0.9.${{ github.run_number }}"
        npm version --no-git-tag-version 0.9.${{ github.run_number }}

    - name: Publish to GitHub Packages
      run: yarn publish --non-interactive
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "0.9.${{ github.run_number }}"  # Use the build number as the tag
        release_name: "Release 0.9.${{ github.run_number }}"
        body: "Release of version 0.9.${{ github.run_number }}."
        draft: false
        prerelease: false

        