name: Publish to GitHub Packages and Create Release

on:
  push:
    branches:
      - main  # Only trigger on commits pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Use Node.js 18 for compatibility
        registry-url: 'https://npm.pkg.github.com'

    - name: Set up .npmrc for GitHub Packages
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
        echo "registry=https://npm.pkg.github.com/<your-username>" >> ~/.npmrc
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # Ensure the token is passed correctly

    - name: Install dependencies with Yarn
      run: yarn install

    - name: Set package version
      run: |
        echo "Updating version to 0.9.${{ github.run_number }}"
        npm version --no-git-tag-version 0.9.${{ github.run_number }}

    - name: Publish to GitHub Packages
      run: yarn publish --non-interactive --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # Ensure the token is passed correctly

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      with:
        tag_name: "0.9.${{ github.run_number }}"
        release_name: "Release 0.9.${{ github.run_number }}"
        body: "Release of version 0.9.${{ github.run_number }}."
        draft: false
        prerelease: false
