name: Publish to GitHub Packages

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        registry-url: 'https://npm.pkg.github.com'

    - name: Install dependencies with Yarn
      run: yarn install

    - name: Publish to GitHub Packages
      run: yarn publish --non-interactive
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
